### ISSUE TITLE
pygame.error: Unable to open file

### ISSUE THREAD

**Issue by 007fred50** [dewittethomas/text-to-speech#6]
Hello,

i'm in raspberry pi

i have installed your plugin (https://pypi.org/project/text-to-speech/ (pip3 install text-to-speech))

but then i try to run some code:
```
from text_to_speech import speak

speak("hello")

```
```
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "helloworld.py", line 1, in <module>
    from text_to_speech import speakee
  File "/home/pi/.local/lib/python3.7/site-packages/text_to_speech/__init__.py", line 1, in <module>
    from .text_to_speech import (
  File "/home/pi/.local/lib/python3.7/site-packages/text_to_speech/text_to_speech.py", line 3, in <module>
    from playsound import playsound
  File "/home/pi/Desktop/python/playsound.py", line 5, in <module>
    Sound = pygame.mixer.Sound('//home/pi/Desktop/python/speech09022021212808.mp3')
pygame.error: Unable to open file '//home/pi/Desktop/python/speech09022021212808.mp3'
```

can you help me out?

**Comment by 007fred50** [comment]
i found out i try to create the same file name in that python directory

**Comment by dewittethomas** [comment]
There was a typo as well: "from text_to_speech import speakee". Maybe that could be the issue too.
